namespace SpriteKind {
    export const myenemy = SpriteKind.create()
    export const myEnimy = SpriteKind.create()
    export const projectile3 = SpriteKind.create()
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (list.length < 6) {
        Projectile2 = sprites.create(img`
            ..............cfff..............
            ............ccddbf..............
            ...........cbddbff.........ccc..
            ..........fccbbcf.........cbbc..
            ...fffffffccccccff.......cdbc...
            .ffcbbbbbbbbbbbbbcfff....cdbf...
            fcbbbbbbbbbcbbbbbbcccff.cdbf....
            fbcbbbbffbbbcbcbbbcccccffdcf....
            fbb1111ffbbbcbcbbbccccccbbcf....
            .fb11111111bbcbbbccccccccbbcf...
            ..fccc33cb11bbbbcccccccfffbbf...
            ...fc131c111bbbcccccbdbc..fbbf..
            ....f33c111cbbccdddddbc....fff..
            .....ff1111fdbbccddbcc..........
            .......cccccfdbbbfcc............
            .............fffff..............
            `, SpriteKind.Projectile)
        Projectile2.setPosition(mySprite.x, mySprite.y)
        Projectile2.ax = -50
        animation.runImageAnimation(
        Projectile2,
        [img`
            .................ccfff..............
            ................cddbbf..............
            ...............cddbbf...............
            ..............fccbbcf............ccc
            ........ffffffccccccff.........ccbbc
            ......ffbbbbbbbbbbbbbcfff.....cdbbc.
            ....ffbbbbbbbbbcbcbbbbcccff..cddbbf.
            ....fbcbbbbbffbbcbcbbbcccccfffdbbf..
            ....fbbb1111ff1bcbcbbbcccccccbbbcf..
            .....fb11111111bbbbbbcccccccccbccf..
            ......fccc33cc11bbbbccccccccfffbbcf.
            .......fc131c111bbbcccccbdbc...fbbf.
            ........f33c111cbbbfdddddcc.....fbbf
            .........ff1111fbdbbfddcc........fff
            ...........cccccfbdbbfc.............
            .................fffff..............
            `,img`
            .................ccfff..............
            ................cddbbf..............
            ...............cddbbf...............
            .........ffffffccbbcf...............
            ......fffbbbbbbbbcccff..............
            .....fbbbbbbbbbbbbbbbcfff......ccccc
            .....bcbbbbbffbcbcbbbbcccff...cdbbbc
            .....bbb1111ffbbcbcbbbcccccffcddbbc.
            .....fb11111111bcbcbbbcccccccbdbbf..
            ......fccc33c11bbbbbbcccccccccbbcf..
            .......fc131cc11bbbbccccccccffbccf..
            ........f33c1111bbbcccccbdbc..fbbcf.
            .........ff1111cbbbfdddddcc....fbbf.
            ...........ccc1fbdbbfddcc.......fbbf
            ..............ccfbdbbfc..........fff
            .................fffff..............
            `,img`
            ..................ccfff.............
            .................cddbbf.............
            ........fffffffffddbbf..............
            .......fbbbbbbbbbfcbcf..............
            .......fbbc111bffbbccffff...........
            .......fb111111ffbbbbbcccff....ccccc
            ........f1cc3311bbcbcbbccccf..cdbbbc
            ........fcc131c1bbbcbcbcccccfcddbbc.
            .........f111111bbbcbcbccccccbdbbf..
            .........f1111111bbbbbccccccccbbcf..
            ..........f111111bbbbcccccccffbccf..
            ...........c1111cbbbcccccbdbc.fbbcf.
            ............cc11cbbbfddddddc...fbbf.
            ..............cffbdbbfdddcc.....fbbf
            .................fbdbbfcc........fff
            ..................fffff.............
            `,img`
            ....................ccfff...........
            ..........fffffffffcbbbbf...........
            .........fbbbbbbbbbfffbf............
            .........fbb111bffbbbbff............
            .........fb11111ffbbbbbcff..........
            .........f1cccc11bbcbcbcccf.........
            ..........fc1c1c1bbbcbcbcccf...ccccc
            ............c3331bbbcbcbccccfccddbbc
            ...........c333c1bbbbbbbcccccbddbcc.
            ...........c331c11bbbbbcccccccbbcc..
            ..........cc13c111bbbbccccccffbccf..
            ..........c111111cbbbcccccbbc.fccf..
            ...........cc1111cbbbfdddddc..fbbcf.
            .............cccffbdbbfdddc....fbbf.
            ..................fbdbbfcc......fbbf
            ...................fffff.........fff
            `,img`
            ...........fffffff...ccfff..........
            ..........fbbbbbbbffcbbbbf..........
            ..........fbb111bbbbbffbf...........
            ..........fb11111ffbbbbff...........
            ..........f1cccc1ffbbbbbcff.........
            ..........ffc1c1c1bbcbcbcccf........
            ...........fcc3331bbbcbcbcccf..ccccc
            ............c333c1bbbcbcbccccfcddbbc
            ............c333c1bbbbbbbcccccddbcc.
            ............c333c11bbbbbccccccbbcc..
            ...........cc331c11bbbbccccccfbccf..
            ...........cc13c11cbbbcccccbbcfccf..
            ...........c111111cbbbfdddddc.fbbcf.
            ............cc1111fbdbbfdddc...fbbf.
            ..............cccfffbdbbfcc.....fbbf
            ....................fffff........fff
            `,img`
            ....................................
            ....................................
            ....................................
            ...............ccffff...............
            ..............cddbbbf...............
            .......ffffffcddbbbf................
            .....ffbbbbbbbbbbbbbcfff.......ccccc
            ...ffbbbbbbbbcbcbbbbbcccff....cdbbbc
            ..fbbbbbbbbbbcbbcbbbbcccccfffcddbbc.
            .fbcbbbbbbbbbbcbcbbbbccccccccbdbbf..
            .fbbbbbbbfffbbcbbbbbccccccccccbbcf..
            .ffbb1111fffbbcbbbbcccccccbcffbccf..
            ..ff111111111bbbbccccccbbbcc..fbbcf.
            ....ccccccc111bdbbbfddbccc.....ffbbf
            ........ccccccfbdbbbfcc..........fff
            ...............ffffff...............
            `],
        100,
        true
        )
        list.push(Projectile2)
    }
    if (true) {
    	
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (list.length < 6) {
        projectile = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . b d b . . . . . . 
            . . . . . . . b d b c . . . . . 
            . . . . b b c 5 5 5 c b b . . . 
            . . . . b 5 5 5 1 5 5 5 b . . . 
            . . . c c 5 5 5 1 5 5 5 c c . . 
            . . b b 5 5 5 1 1 1 5 5 5 b b . 
            . . d d 5 1 1 1 1 1 1 1 5 d d . 
            . . b b 5 5 5 1 1 1 5 5 5 b b . 
            . . . c c 5 5 5 1 5 5 5 c c . . 
            . . . . b 5 5 5 1 5 5 5 b . . . 
            . . . . b b c 5 5 5 c b b . . . 
            . . . . . . c b d b c . . . . . 
            . . . . . . . b d b . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Projectile)
        projectile.setPosition(mySprite.x, mySprite.y)
        list.push(projectile)
    }
    if (true) {
    	
    }
})
info.onCountdownEnd(function () {
    for (let index = 0; index < 10000000; index++) {
        info.startCountdown(100000)
    }
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    if (enemy2.overlapsWith(mySprite)) {
        enemy2.setPosition(30, 30)
    }
    if (enemy3.overlapsWith(mySprite)) {
        enemy3.setPosition(30, 30)
    }
    if (myEnemy.overlapsWith(mySprite)) {
        myEnemy.setPosition(30, 30)
    }
    if (enemy4.overlapsWith(mySprite)) {
        enemy4.setPosition(30, 30)
    }
    if (enemy5.overlapsWith(mySprite)) {
        enemy5.setPosition(30, 30)
    }
    if (enemy6.overlapsWith(mySprite)) {
        enemy6.setPosition(30, 30)
    }
    if (enemy7.overlapsWith(mySprite)) {
        enemy7.setPosition(30, 30)
    }
    if (Enemy8.overlapsWith(mySprite)) {
        Enemy8.setPosition(30, 30)
    }
    if (enemy9.overlapsWith(mySprite)) {
        enemy9.setPosition(30, 30)
    }
    if (enemy10.overlapsWith(mySprite)) {
        enemy10.setPosition(30, 30)
    }
    if (enemy11.overlapsWith(mySprite)) {
        enemy11.setPosition(30, 30)
    }
    if (enemy12.overlapsWith(mySprite)) {
        enemy12.setPosition(30, 30)
    }
    if (enemy13.overlapsWith(mySprite)) {
        enemy13.setPosition(30, 30)
    }
    if (enemy14.overlapsWith(mySprite)) {
        enemy14.setPosition(30, 30)
    }
    if (enemy15.overlapsWith(mySprite)) {
        enemy15.setPosition(30, 30)
    }
    if (enemy16.overlapsWith(mySprite)) {
        enemy16.setPosition(30, 30)
    }
    if (enemy17.overlapsWith(mySprite)) {
        enemy17.setPosition(30, 30)
    }
    if (enemy18.overlapsWith(mySprite)) {
        enemy18.setPosition(30, 30)
    }
    info.changeLifeBy(-1)
})
controller.player2.onEvent(ControllerEvent.Connected, function () {
	
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    for (let value of list) {
        if (enemy2.overlapsWith(value)) {
            enemy2.setPosition(30, 30)
            value.destroy()
            enemy2.destroy()
            list.removeAt(list.indexOf(value))
            enemy3.follow(mySprite, 50)
            enemy3.setPosition(60, 167)
            pause(1000)
            enemy4.follow(mySprite, 50)
            enemy5.follow(mySprite, 50)
            enemy6.follow(mySprite, 50)
            pause(5000)
            enemy7.follow(mySprite, 50)
            Enemy8.follow(mySprite, 50)
            pause(1000)
            enemy4.setPosition(50, 60)
            enemy5.setPosition(60, 120)
            enemy6.setPosition(70, 128)
            pause(5000)
            enemy7.setPosition(60, 150)
            Enemy8.setPosition(60, 200)
            info.changeScoreBy(1)
            break;
        }
        if (enemy3.overlapsWith(value)) {
            enemy3.setPosition(30, 30)
            enemy3.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy4.overlapsWith(value)) {
            enemy4.setPosition(30, 30)
            enemy4.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy5.overlapsWith(value)) {
            enemy5.setPosition(30, 30)
            enemy5.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy6.overlapsWith(value)) {
            enemy6.setPosition(30, 30)
            enemy6.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy7.overlapsWith(value)) {
            enemy7.setPosition(30, 30)
            enemy7.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (Enemy8.overlapsWith(value)) {
            Enemy8.setPosition(30, 30)
            Enemy8.destroy()
            value.destroy()
            game.showLongText("the pirate captain is coming!!", DialogLayout.Bottom)
            music.bigCrash.playUntilDone()
            enemy9.follow(mySprite, 40)
            enemy10.follow(mySprite, 40)
            enemy11.follow(mySprite, 40)
            enemy12.follow(mySprite, 40)
            enemy13.follow(mySprite, 40)
            enemy14.follow(mySprite, 40)
            enemy15.follow(mySprite, 40)
            enemy16.follow(mySprite, 40)
            enemy9.setPosition(20, 250)
            enemy10.setPosition(20, 250)
            enemy11.setPosition(20, 250)
            enemy12.setPosition(20, 250)
            enemy13.setPosition(20, 250)
            enemy14.setPosition(20, 250)
            enemy15.setPosition(20, 250)
            enemy16.setPosition(20, 250)
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy9.overlapsWith(value)) {
            enemy9.setPosition(30, 30)
            enemy9.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy10.overlapsWith(value)) {
            enemy10.setPosition(30, 30)
            enemy10.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy11.overlapsWith(value)) {
            enemy11.setPosition(30, 30)
            enemy11.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy12.overlapsWith(value)) {
            enemy12.setPosition(30, 30)
            enemy12.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy13.overlapsWith(value)) {
            enemy13.setPosition(30, 30)
            enemy13.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy14.overlapsWith(value)) {
            enemy14.setPosition(30, 30)
            enemy14.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy15.overlapsWith(value)) {
            enemy15.setPosition(30, 30)
            enemy15.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy16.overlapsWith(value)) {
            enemy16.setPosition(enemy16.x, enemy16.y)
            enemy16.destroy()
            value.destroy()
            value.destroy()
            value.destroy()
            value.destroy()
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            music.baDing.play()
            game.showLongText("congratulations, you beat the band of pirates and their captain. ", DialogLayout.Bottom)
            game.showLongText("The captain dropped arrows. Use enter to launch arrows at your enemy's.", DialogLayout.Bottom)
            game.showLongText("Click A to go to level two. The pirates have taken the coast and your will go after them and try to steal the treasure on their ship. ", DialogLayout.Bottom)
            tiles.setCurrentTilemap(tilemap`level3`)
            enemy17.follow(mySprite, 50)
            enemy18.follow(mySprite, 50)
            enemy17.setPosition(150, 0)
            enemy18.setPosition(140, 0)
            projectile3.setPosition(140, 10)
        }
        if (enemy17.overlapsWith(value)) {
            value.destroy()
            enemy17.setPosition(160, 90)
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (enemy18.overlapsWith(value)) {
            value.destroy()
            enemy18.setPosition(50, 90)
            list.removeAt(list.indexOf(value))
            info.changeScoreBy(1)
            break;
        }
        if (myEnemy.overlapsWith(value)) {
            myEnemy.setPosition(30, 30)
            value.destroy()
            list.removeAt(list.indexOf(value))
            myEnemy.destroy()
            info.changeScoreBy(1)
            break;
        }
    }
})
let projectile: Sprite = null
let Projectile2: Sprite = null
let list: Sprite[] = []
let projectile3: Sprite = null
let enemy18: Sprite = null
let enemy17: Sprite = null
let enemy16: Sprite = null
let enemy15: Sprite = null
let enemy14: Sprite = null
let enemy13: Sprite = null
let enemy12: Sprite = null
let enemy11: Sprite = null
let enemy10: Sprite = null
let enemy9: Sprite = null
let Enemy8: Sprite = null
let enemy7: Sprite = null
let enemy6: Sprite = null
let enemy5: Sprite = null
let enemy4: Sprite = null
let enemy3: Sprite = null
let enemy2: Sprite = null
let myEnemy: Sprite = null
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level2`)
game.showLongText("monsters are attacking you! fend them off with bombs press space to get a bomb.", DialogLayout.Bottom)
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . c c c c . . . . . . . . 
    . . c c 5 5 5 5 c c . . . . . . 
    . c 5 5 5 5 5 5 5 5 c . . . . . 
    c 5 5 5 5 5 1 f 5 5 5 c . . . . 
    c 5 5 5 5 5 f f 5 5 5 5 c . . . 
    c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
    c c b b 1 b 5 5 5 5 5 5 d c . . 
    c 5 3 3 3 5 5 5 5 5 d d d c . . 
    . b 5 5 5 5 5 5 5 5 d d d c . . 
    . . c b b c 5 5 b d d d d c c . 
    . c b b c 5 5 b b d d d d c d c 
    . c c c c c c d d d d d d d d c 
    . . . c c c c d 5 5 b d d d c . 
    . . c c c c c b 5 5 b c c c . . 
    . . c b b b c d 5 5 b c . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 70, 70)
scene.cameraFollowSprite(mySprite)
info.setLife(5)
mySprite.setPosition(250, 150)
myEnemy = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
myEnemy.setPosition(0, 150)
myEnemy.follow(mySprite, 50)
enemy2 = sprites.create(img`
    . . f f f . . . . . . . . . . . 
    f f f c c . . . . . . . . f f f 
    f f c c c . c c . . . f c b b c 
    f f c 3 c c 3 c c f f b b b c . 
    f f c 3 b c 3 b c f b b c c c . 
    f c b b b b b b c f b c b c c . 
    c c 1 b b b 1 b c b b c b b c . 
    c b b b b b b b b b c c c b c . 
    c b 1 f f 1 c b b c c c c c . . 
    c f 1 f f 1 f b b b b f c . . . 
    f f f f f f f b b b b f c . . . 
    f f 2 2 2 2 f b b b b f c c . . 
    . f 2 2 2 2 2 b b b c f . . . . 
    . . f 2 2 2 b b b c f . . . . . 
    . . . f f f f f f f . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Enemy)
enemy2.setPosition(0, 150)
enemy2.follow(mySprite, randint(10, 100))
enemy3 = sprites.create(img`
    ........................
    ........................
    .......ff...............
    .....ff22ff.............
    ...fff2222fff...........
    ..fff222222fff..........
    ..fff222222fff..........
    ..feeeeeeeeeeff.........
    .ffe22222222eff.........
    .fffffeeeefffff.........
    fdfefbf44fbfeff.........
    fbfe41fddf14ef..........
    fbffe4dddd4efe..........
    fcfef22222f4e...........
    .ff4f44554f4e...........
    ....ffffffdde...........
    .....ffffedde...........
    ..........ee............
    .........ccc............
    ........cc1cc...........
    .........c1c............
    .........c1c............
    .........c1c............
    .........c1c............
    `, SpriteKind.Enemy)
enemy4 = sprites.create(img`
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef............
    .ffffee2222ef...........
    .fe222ffffe2f...........
    fffffffeeefff...........
    ffe44ebf44eef...........
    fee4d41fddef............
    .feee4ddddf.............
    ..fdde444ef.............
    ..fdde22ccc.............
    ...eef22cdc.............
    ...f4444cddc............
    ....fffffcddc...........
    .....fff..cddc..........
    ...........cdc..........
    ............cc..........
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy5 = sprites.create(img`
    .......ff...............
    ....ffff2ff.............
    ..ffeeeef2ff............
    .ffeeeeef22ff...........
    .feeeeffeeeef...........
    .fffffee2222ef..........
    fffe222ffffe2f..........
    ffffffffeeefff..........
    fefe44ebf44eef..........
    .fee4d4bfddef...........
    ..feee4dddee.c..........
    ...f2222eeddeccccccc....
    ...f444e44ddecddddd.....
    ...fffffeeee.ccccc......
    ..ffffffff...c..........
    ..fff..ff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy6 = sprites.create(img`
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff......ccc.
    .ffefbf44fbfeff....cddc.
    .ffefbf44fbfeff...cddc..
    .fee4dddddd4eef.ccddc...
    fdfeeddddd4eeffecddc....
    fbffee4444ee4fddccc.....
    fbf4f222222f1edde.......
    fcf.f222222f44ee........
    .ff.f445544f............
    ....ffffffff............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy7 = sprites.create(img`
    ........................
    .......fff..............
    ....fffff2f.............
    ..ffeeeee22ff...........
    .ffeeeeee222ff..........
    .feeeefffeeeef..........
    .fffffeee2222ef.........
    fffe222fffffe2f.........
    fffffffffeeefff.....cc..
    fefe44ebbf44eef...ccdc..
    .fee4d4bbfddef..ccddcc..
    ..feee4dddddfeecdddc....
    ...f2222222eeddcdcc.....
    ...f444445e44ddccc......
    ...ffffffffeeee.........
    ...fff...ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
Enemy8 = sprites.create(img`
    ..............ffffff....
    .............f2feeeeff..
    ............f222feeeeff.
    .......cc...feeeeffeeef.
    .......cdc.fe2222eeffff.
    .......cddcf2effff222ef.
    ........cddcffeeefffffff
    .........cddce44fbe44eff
    ..........cdceddf14d4eef
    ..........cccdeddd4eeef.
    ...........edd4e44eeff..
    ............ee442222f...
    .............f2e2222f...
    .............f554444f...
    ..............ffffff....
    ................fff.....
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy9 = sprites.create(img`
    ........................
    ........................
    ...999999.......fff.....
    ..9ffffff9.....f55f.....
    .9f2f2f2ff9...f555f.....
    9ff22222fff9.f5555f.....
    999999999999f5555f......
    fee44e1144ff5555f.......
    fee44e1f44f5555f........
    fee4d47777f555f.........
    feeee4777ef555f.........
    .feeee44e4fffff.........
    ..f99999444ee...........
    ..f99999944ee...........
    ..f5555555f.............
    ..f5555555f.............
    ...ffffffff.............
    ....ffffff..............
    .....ffff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy10 = sprites.create(img`
    ........................
    ........................
    ...999999.......fff.....
    ..9ffffff9.....f55f.....
    .9f2f2f2ff9...f555f.....
    9ff22222fff9.f5555f.....
    999999999999f5555f......
    fee44e1144ff5555f.......
    fee44e1f44f5555f........
    fee4d47777f555f.........
    feeee4777ef555f.........
    .feeee44e4fffff.........
    ..f99999444ee...........
    ..f99999944ee...........
    ..f5555555f.............
    ..f5555555f.............
    ...ffffffff.............
    ....ffffff..............
    .....ffff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy11 = sprites.create(img`
    ........................
    ........................
    ...999999.......fff.....
    ..9ffffff9.....f55f.....
    .9f2f2f2ff9...f555f.....
    9ff22222fff9.f5555f.....
    999999999999f5555f......
    fee44e1144ff5555f.......
    fee44e1f44f5555f........
    fee4d47777f555f.........
    feeee4777ef555f.........
    .feeee44e4fffff.........
    ..f99999444ee...........
    ..f99999944ee...........
    ..f5555555f.............
    ..f5555555f.............
    ...ffffffff.............
    ....ffffff..............
    .....ffff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy12 = sprites.create(img`
    ........................
    ........................
    ...999999.......fff.....
    ..9ffffff9.....f55f.....
    .9f2f2f2ff9...f555f.....
    9ff22222fff9.f5555f.....
    999999999999f5555f......
    fee44e1144ff5555f.......
    fee44e1f44f5555f........
    fee4d47777f555f.........
    feeee4777ef555f.........
    .feeee44e4fffff.........
    ..f99999444ee...........
    ..f99999944ee...........
    ..f5555555f.............
    ..f5555555f.............
    ...ffffffff.............
    ....ffffff..............
    .....ffff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy13 = sprites.create(img`
    ........................
    ........................
    ...999999.......fff.....
    ..9ffffff9.....f55f.....
    .9f2f2f2ff9...f555f.....
    9ff22222fff9.f5555f.....
    999999999999f5555f......
    fee44e1144ff5555f.......
    fee44e1f44f5555f........
    fee4d47777f555f.........
    feeee4777ef555f.........
    .feeee44e4fffff.........
    ..f99999444ee...........
    ..f99999944ee...........
    ..f5555555f.............
    ..f5555555f.............
    ...ffffffff.............
    ....ffffff..............
    .....ffff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy14 = sprites.create(img`
    ........................
    ........................
    ...999999.......fff.....
    ..9ffffff9.....f55f.....
    .9f2f2f2ff9...f555f.....
    9ff22222fff9.f5555f.....
    999999999999f5555f......
    fee44e1144ff5555f.......
    fee44e1f44f5555f........
    fee4d47777f555f.........
    feeee4777ef555f.........
    .feeee44e4fffff.........
    ..f99999444ee...........
    ..f99999944ee...........
    ..f5555555f.............
    ..f5555555f.............
    ...ffffffff.............
    ....ffffff..............
    .....ffff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy15 = sprites.create(img`
    ........................
    ........................
    ...999999.......fff.....
    ..9ffffff9.....f55f.....
    .9f2f2f2ff9...f555f.....
    9ff22222fff9.f5555f.....
    999999999999f5555f......
    fee44e1144ff5555f.......
    fee44e1f44f5555f........
    fee4d47777f555f.........
    feeee4777ef555f.........
    .feeee44e4fffff.........
    ..f99999444ee...........
    ..f99999944ee...........
    ..f5555555f.............
    ..f5555555f.............
    ...ffffffff.............
    ....ffffff..............
    .....ffff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy16 = sprites.create(img`
    ........................
    ........................
    ...999999.......fff.....
    ..9ffffff9.....f55f.....
    .9f2f2f2ff9...f555f.....
    9ff22222fff9.f5555f.....
    999999999999f5555f......
    fee44e1144ff5555f.......
    fee44e1f44f5555f........
    fee4d47777f555f.........
    feeee4777ef555f.........
    .feeee44e4fffff.........
    ..f99999444ee...........
    ..f99999944ee...........
    ..f5555555f.............
    ..f5555555f.............
    ...ffffffff.............
    ....ffffff..............
    .....ffff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy17 = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
enemy18 = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
projectile3 = sprites.create(img`
    . . 6 6 6 6 . . 
    . 6 d 4 4 4 6 . 
    6 1 b 1 1 4 d 6 
    c 1 b b 4 4 1 c 
    . c b b b d c . 
    . . c c c c . . 
    `, SpriteKind.Projectile)
enemy3.setPosition(2, 0)
enemy4.setPosition(2, 0)
enemy5.setPosition(2, 0)
enemy6.setPosition(2, 0)
enemy7.setPosition(2, 0)
Enemy8.setPosition(2, 0)
enemy9.setPosition(2, 0)
enemy10.setPosition(2, 0)
enemy11.setPosition(2, 0)
enemy12.setPosition(2, 0)
enemy13.setPosition(2, 0)
enemy14.setPosition(2, 0)
enemy15.setPosition(2, 0)
enemy16.setPosition(-2150, -90900)
enemy17.setPosition(2, 0)
enemy18.setPosition(2, 0)
list = []
animation.runImageAnimation(
enemy3,
[img`
    ........................
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef...cc.......
    .ffffee2222ef.cdc.......
    .fe222ffffe2fcddc.......
    fffffffeeeffcddc........
    ffe44ebf44ecddc.........
    fee4d41fddecdc..........
    .feee4dddedccc..........
    ..ffee44e4dde...........
    ...f222244ee............
    ...f2222e2f.............
    ...f444455f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `,img`
    ........................
    .......fff..............
    ....fffff2f.............
    ..ffeeeee22ff...........
    .ffeeeeee222ff..........
    .feeeefffeeeef..........
    .fffffeee2222ef.........
    fffe222fffffe2f.........
    fffffffffeeefff.....cc..
    fefe44ebbf44eef...ccdc..
    .fee4d4bbfddef..ccddcc..
    ..feee4dddddfeecdddc....
    ...f2222222eeddcdcc.....
    ...f444445e44ddccc......
    ...ffffffffeeee.........
    ...fff...ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `,img`
    .......ff...............
    ....ffff2ff.............
    ..ffeeeef2ff............
    .ffeeeeef22ff...........
    .feeeeffeeeef...........
    .fffffee2222ef..........
    fffe222ffffe2f..........
    ffffffffeeefff..........
    fefe44ebf44eef..........
    .fee4d4bfddef...........
    ..feee4dddee.c..........
    ...f2222eeddeccccccc....
    ...f444e44ddecddddd.....
    ...fffffeeee.ccccc......
    ..ffffffff...c..........
    ..fff..ff...............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `,img`
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef............
    .ffffee2222ef...........
    .fe222ffffe2f...........
    fffffffeeefff...........
    ffe44ebf44eef...........
    fee4d41fddef............
    .feee4ddddf.............
    ..fdde444ef.............
    ..fdde22ccc.............
    ...eef22cdc.............
    ...f4444cddc............
    ....fffffcddc...........
    .....fff..cddc..........
    ...........cdc..........
    ............cc..........
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `],
200,
true
)
animation.runImageAnimation(
mySprite,
[img`
    ........................
    ........................
    ...........cc...........
    .........cccc...........
    .....ccccccc...cc.......
    ...cc555555cccccc.......
    ..c5555555555bcc........
    .c555555555555b..cc.....
    c555551ff555555bccc.....
    c55d55ff55555555bcc.....
    c5555555555555555b......
    .cbb31bb55555d555b..c...
    .c5333bb55ddddd55dccc...
    .c533b55ddddddddddbc....
    .c5555ddddb55bdddddccc..
    ..ccccbbbb555bdddddccc..
    ...cdcbc5555bddddddcc...
    ....ccbc55bcdddddddbcccc
    .....cbbccbd55dddddddddc
    .....ccbbbd555ddddddddbc
    ...ccbdcbb555ddbbdddbcc.
    ...cbdddcc55ddbbbbccc...
    ...cccccccbdddbccc......
    ........cd555ddc........
    `,img`
    ........................
    ........................
    ..........ccc...........
    .........cccc...........
    .....ccccccc..ccc.......
    ...cc555555cccccc.......
    ..c5555555555bcc........
    .c555555555555b..cc.....
    c555551ff555555bccc.....
    c55d55ff55555555bc......
    c5555555555555555b......
    .cbb31bb5555dd555b.cc...
    .c5333b555ddddd55dccc...
    .c533b55ddddddddddb.....
    .c5555dddbb55bdddddccc..
    ..ccccbbbb555bdddddccc..
    ...cdcbc5555bddddddcc...
    ....ccbc55bc5ddddddbcccc
    .....cbbcc5555dddddddddc
    .....ccbbb555ddbddddddc.
    .....cdcbc55ddbbbdddcc..
    ...ccdddccddddbcbbcc....
    ...ccccccd555ddccc......
    ........cccccccc........
    `,img`
    ........................
    ..........cc............
    .........ccc............
    .....ccccccc.ccc........
    ...cc555555ccccc........
    ..c5555555555bcc........
    .c55551ff55555b.ccc.....
    c55555ff5555555bccc.....
    c55d555555555555bc......
    c55555bb555555555b.c....
    .cbb31b5555ddd555bcc....
    .c5333b555ddddd55dcc....
    .c533b55ddddddd5ddc.....
    ..c555dbbb555bddddb.c...
    ...cccb55555bbdddddcc...
    ....ccb555ccdddddddcc...
    ..ccccbcccbddddddddcc...
    ..c55cbbbbd55dddddddbcc.
    ...c5ccbbd555dddddddddcc
    ....cccbb555ddbbbddddddc
    ......ccb55ddbbbbddddcc.
    ....ccddcbdddbbbbbccc...
    ....ccccd555ddccccc.....
    ........cccccc..........
    `,img`
    ........................
    ..........cc............
    .........ccc............
    .....ccccccc.ccc........
    ...cc555555ccccc........
    ..c5555555555bcc........
    .c55551ff55555b.ccc.....
    c55555ff5555555bccc.....
    c55d555555555555bc......
    c55555bb555555555b.c....
    .cbb31b5555ddd555bcc....
    .c5333b555ddddd55dcc....
    .c533b55ddddddd5ddc.....
    ..c555dbbb555bddddb.c...
    ...cccb55555bbdddddcc...
    ....ccb555ccdddddddcc...
    ..ccccbcccdddddddddcccc.
    ..c55cbbbd55ddddddddcdc.
    ...c5cccd555ddddddddddc.
    ....cc555d5ddbbbbddddbc.
    ......5555ddbbbbbdddbc..
    ......c5555dbbbbbbccc...
    .......c555cccccccc.....
    ........ccc.............
    `,img`
    ........................
    ..........cc............
    .........ccc............
    .....ccccccc.ccc........
    ...cc555555ccccc........
    ..c5555555555bcc........
    .c55551ff55555b.ccc.....
    c55555ff5555555bccc.....
    c55d555555555555bc......
    c55555bb555555555b.c....
    .cbb31b5555ddd555bcc....
    .c5333b555ddddd55dcc....
    .c533b55ddddddd5ddc.....
    ..c555dbbb555bddddb.c...
    ...cccb555555bdddddcc...
    ....ccb5555ccddddddccc..
    ..ccccbcccbddddddddccdc.
    ..c55cbbbbdddddddddbddc.
    ...c5cbbbd55ddddddddddc.
    ....cccbdd55dbbbbddddbc.
    .....cccd555dbbbbdddbc..
    .....c555dddbbbbbbccc...
    .....c55555dbcccccc.....
    ......c5555cc...........
    `,img`
    ........................
    ..........cc............
    .........ccc............
    .....ccccccc..cc........
    ...cc555555ccccc........
    ..c5555555555bcc........
    .c555555555555b..cc.....
    c555551ff555555bccc.....
    c55d55ff55555555bc......
    c5555555555555555b......
    .cbb31bb5555dd555b.cc...
    .c5333b555ddddd55dccc...
    .c533b55ddddddd5ddcc....
    .c5555ddddb55bddddb.....
    ..ccccbbbbb55bdddddccc..
    ..ccccbc5555bddddddcccc.
    ..c55cbc555cdddddddccdc.
    ...c5cbbcccdddddddddddc.
    ....cccbbbbd55dddddddbc.
    ....cbcbbbd555ddddddbcc.
    .....cccbb555dbbbddccc..
    .......cc555dbbbbbcc....
    .......cbddddbcccc......
    ......cd5555dc..........
    `],
100,
true
)
animation.runImageAnimation(
myEnemy,
[img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `,img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111ffff.....
    ......fffcdb1bc111cf....
    ....fc111cbfbf1b1b1f....
    ....f1b1b1ffffbfbfbf....
    ....fbfbfffffff.........
    .........fffff..........
    ..........fff...........
    ........................
    ........................
    ........................
    ........................
    `,img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `,img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .....ffff111111bf.......
    ....fc111cdb1bdfff......
    ....f1b1bcbfbfc111cf....
    ....fbfbfbffff1b1b1f....
    .........fffffffbfbf....
    ..........fffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `],
200,
true
)
forever(function () {
	
})
